name: Windows RDP Setup

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          powershell -Command "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0"
          powershell -Command "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
          powershell -Command "net user github $env:USER_PASSWORD /add"
          powershell -Command "net localgroup administrators github /add"
          powershell -Command "net user github $env:USER_PASSWORD"

      - name: Show External IP
        run: |
          curl ifconfig.me

      - name: Show connection info
        run: |
          echo "RDP Enabled. Use IP from above and username 'github'."
